# ----------------------------------------------------------------
# Server Codes
# ----------------------------------------------------------------

OPCODE_REGISTER = 1000
OPCODE_GET_CLIENTS_LIST = 1001
OPCODE_GET_CLIENT_PUBLIC_KEY = 1002
OPCODE_SEND_MESSAGE = 1003
OPCODE_GET_PENDING_MESSAGES = 1004



RESPONSE_CODE_REGISTER = 2000
RESPONSE_CODE_GET_CLIENTS_LIST = 2001
RESPONSE_CODE_GET_CLIENT_PUBLIC_KEY = 202
RESPONSE_CODE_SEND_MESSAGE = 2003
RESPONSE_CODE_GET_PENDING_MESSAGES = 2004



